### ISSUE TITLE
Error on linter @import

### ISSUE THREAD

**Issue by exdeniz** [olmokramer/atom-linter-stylus#1]
Linter show error on @import "failed to locate @import...bla bla"
i try
```stylus
@import "banner/banner"
@import "./banner/banner"
@import "./banner/banners.styl"
@import "banner/banners.styl"
```
and show еру error still

**Comment by olmokramer** [comment]
I fixed this one for @imports relative to the linted file.

You can, however, give Stylus a `paths` option with directories to look in for relative @imports. I can't find out what the `paths` variable is in your build system though, so that's more difficult. Maybe I can look for a file in the projects root directory, `linter-stylus.json` or whatever, that can define the `paths`.

**Comment by exdeniz** [comment]
I't is work. Thanks.
